server:
  port: 9000

logging:
    org.springframework.security: TRACE
    org:springframework.web: TRACE
    com.fabiankevin.springboot_authorization_server: DEBUG

spring:
  application:
    name: authorization-server

