spring:
  application:
    name: springboot-herbs-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
          jwk-set-uri: "https://localhost:9000/oauth2/v1/jwks"

server:
  port: 8090


logging:
  level:
    org.springframework.security: DEBUG
    org:springframework.web: DEBUG
    com.fabiankevin.springboot_herbs_resource_server: DEBUG
