spring:
  application:
    name: springboot-herbs-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000

server:
  port: 8090


logging:
  level:
    org.springframework.security: TRACE
    org:springframework.web: TRACE
    com.fabiankevin.springboot_herbs_resource_server: DEBUG
