server:
  port: 8089
spring:
  application:
    name: springboot-oaut2-login-and-client
  security:
    oauth2:
      client:
        registration:
          herb:
            registrationId: Herb
            client-id: client12345
            client-secret: client12345-secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8089/login/oauth2/code/herb
            scope: openid
        provider:
          herb:
            issuer-uri: http://localhost:9000
            authorization-uri: http://127.0.0.1:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            user-info-uri: http://localhost:9000/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9000/oauth2/jwks

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    com.fabiankevin.springboot_oaut2_login_and_client: DEBUG